### ISSUE TITLE
Unexpected result with time.mktime

### ISSUE THREAD

**Issue by azmeuk** [pokidovea/immobilus#9]
A new one :) The `time.mktime` function [takes a local time argument](https://docs.python.org/2/library/time.html#time.mktime) and returns a timestamp.

```python
# dt.py

import immobilus, datetime, time
with immobilus.immobilus("1970-01-01 00:00:00"):
    timetuple = datetime.datetime.now().timetuple()
    print(timetuple)

    mktime = time.mktime(timetuple)
    print(mktime)
```
```bash
$ env TZ=UTC-1 python dt.py
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=-1)
-3600.0
```
The expected value of `time.mktime` is `0` but it seems the system timezone is used over the `tz_offset` value.

**Comment by pokidovea** [comment]
See https://github.com/pokidovea/immobilus/pull/10

**Comment by azmeuk** [comment]
Just tested, it seems great!

**Comment by pokidovea** [comment]
Done https://pypi.python.org/pypi/immobilus/0.2.11

**Comment by azmeuk** [comment]
Hm. Actually I am still getting a misbehavior, but I am not sure why.
```python
def test():
    now = datetime.datetime.now()
    timetuple = now.timetuple()
    mktime = time.mktime(timetuple)
    fromtimestamp = datetime.datetime.fromtimestamp(mktime)
    print(now)
    print(fromtimestamp)
test()
```

No matter what timezone is used when running this script with `env TZ=UTC-2 python dt.py` it always display the same thing twice. But when I mock this function with immobilus, the late result is different.

**Comment by pokidovea** [comment]
Sounds strange. The file below works as expected with commented and uncommented immobilus
```python
from immobilus.logic import immobilus

import time
from datetime import datetime


def test():
    # with immobilus('2017-01-01 00:00:00'):
    now = datetime.now()
    timetuple = now.timetuple()
    mktime = time.mktime(timetuple)
    fromtimestamp = datetime.fromtimestamp(mktime)

    assert now.replace(microsecond=0) == fromtimestamp
    print(now)
    print(fromtimestamp)

test()
```

Results with commented line:
```
$ TZ=UTC-2 python dt.py
2017-09-13 17:40:52.998957
2017-09-13 17:40:52
```

Results with uncommented line:
```
$ TZ=UTC-2 python dt.py  
2017-01-01 00:00:00
2017-01-01 00:00:00
```

Which python version do you use? I've tested on 3.5.1

**Comment by azmeuk** [comment]
I forgot to say, results differ if you use a timezone offset.

```python
# dt_natural.py
import immobilus, time, datetime

def test():
    now = datetime.datetime.now()
    mktime = time.mktime(now.timetuple())
    fromtimestamp = datetime.datetime.fromtimestamp(mktime)

    print(now)
    print(fromtimestamp)

test()
```
```python
# dt_mocked.py
import immobilus, time, datetime

def test():
    now = datetime.datetime.now()
    mktime = time.mktime(now.timetuple())
    fromtimestamp = datetime.datetime.fromtimestamp(mktime)

    print(now)
    print(fromtimestamp)

with immobilus.immobilus(datetime.datetime.utcnow(), tz_offset=2):
    test()
```

```bash
$ env TZ=UTC-2 python dt_natural.py
2017-09-13 19:46:43.930219
2017-09-13 19:46:43

$ python dt_mocked.py                                                                                                                                           
2017-09-13 19:46:44.575760
2017-09-13 21:46:44
```

The first script kinda "mocks" the system timezones, but date are the same, no matter what timezone is used. With the second script, the timezone is mocked by immobilus, but the dates differ.

**Comment by pokidovea** [comment]
I found. It happens because tz_offset affects on datetime.fromtimestamp(mktime).
I think it would be better to remove this line https://github.com/pokidovea/immobilus/blob/master/immobilus/logic.py#L215

What do you think?

**Comment by pokidovea** [comment]
Please, check the behaviour in issue_9 branch. https://github.com/pokidovea/immobilus/tree/issue_9

**Comment by azmeuk** [comment]
I will try to look at this tomorrow or the day after.

**Comment by pokidovea** [comment]
merged. Check from master.

**Comment by pokidovea** [comment]
I've fixed mktime behaviour. Please, try out version 0.2.15 from pypi.
